// const twoHundredHoursToMilsec = 200 * 60 * 60 * 1000;
// const todayDateMilsec = new Date().getTime();
// const twoHundredHoursBackMilsec = Number(todayDateMilsec) - twoHundredHoursToMilsec;

export const chunkArray = (arr, size) => (arr.length > size ? [arr.slice(0, size), ...chunkArray(arr.slice(size), size)] : [arr]);

const tryArr = [
    {
        finishedTime: new Date("Sun Mar 26 2023 01:00:00 GMT+0200"),
        finishedHour: 1,
        finishedDay: 26,
        month: 3,
        year: 2023,
        openPrice: "27432.9",
        closePrice: "27444.9",
        priceChangedFor1Hour: {
            className: "positive",
            value: "0.04",
        },
    },
];

function fillMissedDateObjects(arr) {
    for (let i = 0; i < arr.length; i++) {
        const currentCoinObj = arr[i];
        const nextCoinObj = arr[i + 1];
        const nextCoinObjActualFinishedTime = Number(nextCoinObj.finishedHour);
        const nextCoinObjCorrectFinishedTime = Number(currentCoinObj.finishedHour) + 1;

        if (nextCoinObjActualFinishedTime !== nextCoinObjCorrectFinishedTime) {
            console.warn("У следуюшего обьекта после этого, отсутсвует корректное время: ", currentCoinObj);
            console.warn("Индекс этого обьекта: ", i);
            const newCustomCoinObj = structuredClone(currentCoinObj);
            newCustomCoinObj.finishedTime.setHours(Number(currentCoinObj.finishedHour) + 1);
            newCustomCoinObj.finishedHour = Number(currentCoinObj.finishedHour) + 1;
            newCustomCoinObj.fakelyCreated = true;
            // Insert at exact position
            arr.splice(i + 1, 0, newCustomCoinObj);
        }
    }
    return arr;
}

// console.log(fillMissedDateObjects(tryArr));

export function calcPercentageDifference(closedPrice, openedPrice) {
    closedPrice = Number(closedPrice);
    openedPrice = Number(openedPrice);
    const result = ((closedPrice - openedPrice) / openedPrice) * 100;
    const className = Number(result) > 0 ? "positive" : "negative";
    return { className: className, value: result.toFixed(4) };
}

export const UPDATED_FUTURES_TICKERS = [
    "SUI",
    "HIVE",
    "AI16Z",
    "ADA",
    "1000PEPE",
    "AIXBT",
    "AGLD",
    "VIRTUAL",
    "XLM",
    "SONIC",
    "ENA",
    "FARTCOIN",
    "WIF",
    "SWARMS",
    "HYPE",
    "USUAL",
    "POPCAT",
    "LINK",
    "CGPT",
    "HBAR",
    "SPX",
    "GALA",
    "TIA",
    "MOVE",
    "ZEREBRO",
    "COOKIE",
    "ONDO",
    "SHIB1000",
    "GAS",
    "PENGU",
    "MOCA",
    "IOTA",
    "AVAX",
    "WLD",
    "UXLINK",
    "RUNE",
    "STMX",
    "AAVE",
    "LTC",
    "GOAT",
    "BAN",
    "ALGO",
    "BSV",
    "NOT",
    "STEEM",
    "APT",
    "CRV",
    "PNUT",
    "ARB",
    "1000BONK",
    "INJ",
    "UNI",
    "DOT",
    "ORDI",
    "SEI",
    "NEAR",
    "FLOCK",
    "GRIFFAIN",
    "AVAIL",
    "STG",
    "BIO",
    "MTL",
    "SAND",
    "RENDER",
    "TAO",
    "ALCH",
    "HIFI",
    "OP",
    "PUFFER",
    "BCH",
    "ATOM",
    "GLM",
    "ARK",
    "MORPHO",
    "TON",
    "KAS",
    "CHILLGUY",
    "BNB",
    "HIPPO",
    "GMT",
    "BRETT",
    "POWR",
    "EIGEN",
    "COMP",
    "ORDER",
    "ARC",
    "MOODENG",
    "JASMY",
    "AERO",
    "ME",
    "ENS",
    "DEXE",
    "DYDX",
    "DRIFT",
    "FWOG",
    "ACT",
    "STORJ",
    "VANA",
    "APE",
    "DEEP",
    "1000000MOG",
    "ICP",
    "IOST",
    "TRX",
    "CTC",
    "VELO",
    "JUP",
    "PENDLE",
    "ZEN",
    "FIL",
    "FUEL",
    "PHA",
    "TAI",
    "GRASS",
    "THETA",
    "EOS",
    "STX",
    "OM",
    "1000FLOKI",
    "POL",
    "LDO",
    "NEO",
    "MBL",
    "ETC",
    "AR",
    "DOGS",
    "LSK",
    "SUSHI",
    "IO",
    "AI",
    "MNT",
    "COW",
    "AERGO",
    "OL",
    "T",
    "CLOUD",
    "ZRO",
    "ZRX",
    "VET",
    "BLUE",
    "ATH",
    "REN",
    "ADA",
    "HMSTR",
    "DEGEN",
    "SXP",
    "RIFSOL",
    "STPT",
    "XVG",
    "STRK",
    "CVC",
    "BAT",
    "1000CAT",
    "XTZ",
    "AXS",
    "TRB",
    "GRT",
    "JTO",
    "KNC",
    "CHZ",
    "URO",
    "L3",
    "ONG",
    "MOTHER",
    "ARKM",
    "1000RATS",
    "BOME",
    "WAVES",
    "PONKE",
    "BEAM",
    "SNT",
    "LUCE",
    "SAFE",
    "ANKR",
    "10000SATS",
    "POLYX",
    "GIGA",
    "KMNO",
    "MEW",
    "GOMINING",
    "1000000BABYDOGE",
    "ONE",
    "BLAST",
    "ZK",
    "KEY",
    "TOKEN",
    "PRIME",
    "KAIA",
    "FLOW",
    "BLUR",
    "TAIKO",
    "W",
    "MANA",
    "PEOPLE",
    "RSR",
    "WOO",
    "AGI",
    "LUMIA",
    "PEAQ",
    "ICX",
    "MEME",
    "CVX",
    "NEIROETH",
    "PYTH",
    "MEMEFI",
    "WAXP",
    "TROY",
    "IMX",
    "SUNDOG",
    "SOLO",
    "MVL",
    "CETUS",
    "1INCH",
    "ETHFI",
    "AIOZ",
    "ZIL",
    "REX",
    "KAVA",
    "MAGIC",
    "BIGTIME",
    "XAI",
    "BANANA",
    "AKT",
    "QNT",
    "CATI",
    "FLR",
    "MYRO",
    "ZETA",
    "EGLD",
    "XMR",
    "SC",
    "ORBS",
    "CRO",
    "G",
    "MKR",
    "HNT",
    "ZRC",
    "OMNI",
    "KOMA",
    "SCR",
    "ONT",
    "1000X",
    "XION",
    "SD",
    "MANTA",
    "THE",
    "SEND",
    "ALEO",
    "LPT",
    "QTUM",
    "1000000CHEEMS",
    "SPEC",
    "DGB",
    "MAJOR",
    "AVA",
    "ATA",
    "ZEC",
    "KSM",
    "CFX",
    "MASK",
    "ID",
    "PROS",
    "ZENT",
    "SUPER",
    "CARV",
    "ROSE",
    "CKB",
    "AUCTION",
    "SNX",
    "CORE",
    "MINA",
    "CAKE",
    "MAVIA",
    "VRA",
    "DYM",
    "SWELL",
    "GEMS",
    "VANRY",
    "BB",
    "COTI",
    "SLERF",
    "YFI",
    "SAGA",
    "DOT/USD",
    "MASA",
    "LINA",
    "TNSR",
    "ILV",
    "FORTH",
    "XEM",
    "LUNA2",
    "FTN",
    "REEF",
    "A8",
    "NFP",
    "LTC",
    "BNX",
    "UMA",
    "ASTR",
    "ALT",
    "NS",
    "AEVO",
    "SCRT",
    "CELO",
    "ORCA",
    "XNO",
    "SCA",
    "CTK",
    "PRCL",
    "C98",
    "ZEUS",
    "1000MUMU",
    "CYBER",
    "SUN",
    "GMX",
    "ALPHA",
    "SSV",
    "CHR",
    "KDA",
    "IDEX",
    "JST",
    "ENJ",
    "TWT",
    "VELODROME",
    "FXS",
    "AXL",
    "BILLY",
    "METIS",
    "FLM",
    "SLP",
    "DASH",
    "FOXY",
    "API3",
    "ACE",
    "BADGER",
    "ACX",
    "HIGH",
    "ALICE",
    "ETHW",
    "LOOKS",
    "OG",
    "FB",
    "USDC",
    "PORTAL",
    "MDT",
    "OXT",
    "YGG",
    "GLMR",
    "TRU",
    "MOBILE",
    "MYRIA",
    "SYN",
    "RARE",
    "10000LADYS",
    "RSS3",
    "ACH",
    "RDNT",
    "XVS",
    "AUDIO",
    "FIDA",
    "BAND",
    "GME",
    "DENT",
    "LISTA",
    "MERL",
    "FIRE",
    "1CAT",
    "REZ",
    "XCH",
    "HOT",
    "JOE",
    "LQTY",
    "SKL",
    "HOOK",
    "BAKE",
    "DBR",
    "LIT",
    "CELR",
    "OMG",
    "RVN",
    "BICO",
    "SFP",
    "COOK",
    "PERP",
    "REQ",
    "MON",
    "LRC",
    "PHB",
    "FLUX",
    "MBOX",
    "PAXG",
    "GTC",
    "HPOS10I",
    "MAV",
    "MOVR",
    "MANEKI",
    "LEVER",
    "NMR",
    "XCN",
    "USTC",
    "SLF",
    "CHESS",
    "PIRATE",
    "DUSK",
    "OGN",
    "PIXEL",
    "EDU",
    "1000TOSHI",
    "BSW",
    "NYAN",
    "F",
    "BENDOG",
    "HFT",
    "VTHO",
    "COS",
    "PENG",
    "RIF",
    "DATA",
    "SWEAT",
    "IOTX",
    "FIO",
    "RLC",
    "VIDT",
    "SYS",
    "RAD",
    "PYR",
    "OSMO",
    "SILLY",
    "RPL",
    "ZBCN",
    "BEL",
    "ARPA",
    "EOS",
    "RON",
    "PROM",
    "NULS",
    "SPELL",
    "NKN",
    "BOBA",
    "AMB",
    "TLM",
    "DODO",
    "BAL",
    "BNT",
    "VOXEL",
    "QI",
    "NTRN",
    "ALPACA",
    "XRD",
    "MANA/USD",
    "CTSI",
    "GODS",
    "LTO",
    "QUICK",
    "GNO",
    "FDUSD",
    "FTM",
    "10000WHY",
    "1000000PEIPEI",
];

export const ALL_LISTING_TICKERS = [
    "FLOCK",
    // "SONIC",
    // "AI16Z",
    // "FUEL",
    // "PENGU",
    "LUNA2",
    // "VANA",
    // "AERO",
    // "SEND",
    // "ZEREBRO",
    // "ME",
    // "MOVE",
    // "F",
    // "XION",
    // "MAJOR",
    // "LUCE",
    // "CHILLGUY",
    // "ZRC",
    // "MEMEFI",
    // "PNUT",
    // "MORPHO",
    // "SPX",
    // "VIRTUAL",
    "NEIROETH",
    // "OL",
    "STOP",
    // "BAN",
    "CMETH",
    // "NS",
    // "GOAT",
    // "SWELL",
    "SMILE",
    "BBQ",
    // "KAIA",
    "KRO",
    // "COOK",
    // "GRASS",
    "X",
    // "SCR",
    "PUFF",
    // "DBR",
    // "PUFFER",
    // "DEEP",
    "BBSOL",
    // "CARV",
    "ZAP",
    "CATS",
    "NAVX",
    // "EIGEN",
    "DAPP",
    // "HMSTR",
    "SOCIAL",
    // "CATI",
    // "SUNDOG",
    "MAK",
    // "DOGS",
    // "ORDER",
    // "G",
    // "RENDER",
    // "AVAIL",
    "ZKL",
    // "CLOUD",
    // "PIXFI",
    // "UXLINK",
    // "A8",
    // "MOCA",
    "WELL",
    "PTC",
    "MCG",
    "ZEX",
    "TST",
    // "BLAST",
    "NRN",
    // "POPCAT",
    // "ZRO",
    "XZK",
    // "COOKIE",
    // "ZK",
    // "PIRATE",
    // "ATH",
    // "IO",
    "AARK",
    "AURORA",
    "ULTI",
    // "TAIKO",
    "MOG",
    "APTR",
    "ELIX",
    "PARAM",
    // "MON",
    "HLG",
    // "NYAN",
    "NUTS",
    "SQD",
    // "NOT",
    "NLK",
    // "DRIFT",
    "CTA",
    "BUBBLE",
    // "BB",
    // "PONKE",
    "GALAXIS",
    "MODE",
    // "SPEC",
    "ZERO",
    // "TAI",
    // "ZENT",
    // "WIF",
    "SVL",
    "GUMMY",
    "LAI",
    "EXVG",
    "LL",
    "PBUX",
    "SAFE",
    "MERL",
    "MEW",
    "BRETT",
    "MSTAR",
    "PRCL",
    "FOXY",
    "BLOCK",
    "ESE",
    "MASA",
    "G3",
    "TNSR",
    "MOJO",
    "EVERY",
    "VELAR",
    "W",
    "XAR",
    "BONUS",
    "USDE",
    "MFER",
    "ENA",
    "DEGEN",
    "WEN",
    "GMRX",
    "APRS",
    "VENOM",
    "NAKA",
    "FLT",
    "ZK",
    "AURY",
    "ETHFI",
    "BOME",
    "ZEND",
    "AEVO",
    "NGL",
    "STAR",
    "NIBI",
    "SCA",
    "QORPO",
    "PORTAL",
    "BBL",
    "SQT",
    "CSPR",
    "CPOOL",
    "BCUT",
    "STRK",
    "HTX",
    "DYM",
    "MAVIA",
    "MXM",
    "FIRE",
    "JUP",
    "DEFI",
    "DMAIL",
    "AFG",
    "GTAI",
    "FAR",
    "SAROS",
    "ONDO",
    "MANTA",
    "APP",
    "DUEL",
    "SQR",
    "VIC",
    "XAI",
    "AEG",
    "ZETA",
    "MYRO",
    "ALT",
    "RATS",
    "SATS",
    "PORT3",
    "ZKF",
    "VPR",
    "AIOZ",
    "KCS",
    "FLIP",
    "GG",
    "COQ",
    "TRC",
    "AKI",
    "MBOX",
    "IRL",
    "MYRIA",
    "FMC",
    "KUB",
    "CBK",
    "VANRY",
    "5IRE",
    "ROOT",
    "RPK",
    "SHRAP",
    "TOKEN",
    "MEME",
    "TIA",
    "BEAM",
    "ZTX",
    "CAT",
    "LEVER",
    "KAS",
    "ORDI",
    "SEI",
    "CYBER",
    "SEILOR",
    "SPARTA",
    "NYM",
    "PENDLE",
    "VELA",
    "ZIG",
    "METH",
    "JTO",
    "INSP",
    "MLK",
    "VRTX",
    "PYTH",
    "POL",
    "PPT",
    "JEFF",
    "FET",
    "NESS",
    "NEXT",
    "CTT",
    "KAVA",
    "SAIL",
    "TAVA",
    "DSRUN",
    "PLANET",
    "WLD",
    "GSWIFT",
    "SALD",
    "ARKM",
    "ELDA",
    "TENET",
    "EGO",
    "NEON",
    "MNT",
    "VELO",
    "ARTY",
];

// export const listingSPOTTickers1 = [
//     "FLOCK",
//     "XTER",
//     "SONIC",
//     "SERAPH",
//     "AI16Z",
//     "ODOS",
//     "FUEL",
//     "MNRY",
//     "FLUID",
//     "PENGU",
//     "STREAM",
//     "CAT",
//     "LUNA",
//     "VANA",
//     "AERO",
//     "SEND",
//     "ZEREBRO",
//     "ME",
//     "MOZ",
//     "MOVE",
//     "F",
//     "XION",
//     "MAJOR",
//     "SUPRA",
//     "THRUST",
//     "LUCE",
//     "CHILLGUY",
//     "ZRC",
//     "MEMEFI",
//     "PNUT",
//     "MORPHO",
//     "SPX",
//     "VIRTUAL",
//     "NEIRO",
//     "OL",
//     "STOP",
//     "BAN",
//     "CMETH",
//     "NS",
//     "GOAT",
//     "SWELL",
//     "SMILE",
//     "BBQ",
//     "KAIA",
//     "KRO",
//     "COOK",
//     "GRASS",
//     "X",
//     "SCR",
//     "PUFF",
//     "DBR",
//     "PUFFER",
//     "DEEP",
//     "BBSOL",
//     "CARV",
//     "ZAP",
//     "CATS",
//     "NAVX",
//     "EIGEN",
//     "DAPP",
//     "HMSTR",
//     "SOCIAL",
//     "CATI",
//     "SUNDOG",
//     "MAK",
//     "DOGS",
//     "ORDER",
//     "G",
//     "RENDER",
//     "AVAIL",
//     "ZKL",
//     "CLOUD",
//     "PIXFI",
//     "UXLINK",
//     "A8",
//     "MOCA",
//     "WELL",
//     "PTC",
//     "MCG",
//     "ZEX",
//     "TST",
//     "BLAST",
//     "NRN",
//     "POPCAT",
//     "ZRO",
//     "XZK",
//     "COOKIE",
//     "ZK",
//     "PIRATE",
//     "ATH",
//     "IO",
//     "AARK",
//     "AURORA",
//     "ULTI",
//     "TAIKO",
//     "MOG",
//     "APTR",
//     "ELIX",
//     "PARAM",
//     "MON",
// ];

// export const listingSPOTTickers2 = [
//     "HLG",
//     "NYAN",
//     "NUTS",
//     "SQD",
//     "NOT",
//     "NLK",
//     "DRIFT",
//     "CTA",
//     "BUBBLE",
//     "BB",
//     "PONKE",
//     "GALAXIS",
//     "MODE",
//     "SPEC",
//     "ZERO",
//     "TAI",
//     "ZENT",
//     "WIF",
//     "SVL",
//     "GUMMY",
//     "LAI",
//     "EXVG",
//     "LL",
//     "PBUX",
//     "SAFE",
//     "MERL",
//     "MEW",
//     "BRETT",
//     "MSTAR",
//     "PRCL",
//     "FOXY",
//     "BLOCK",
//     "ESE",
//     "MASA",
//     "G3",
//     "TNSR",
//     "MOJO",
//     "EVERY",
//     "VELAR",
//     "W",
//     "XAR",
//     "BONUS",
//     "USDE",
//     "MFER",
//     "ENA",
//     "DEGEN",
//     "WEN",
//     "GMRX",
//     "APRS",
//     "VENOM",
//     "NAKA",
//     "FLT",
//     "ZK",
//     "AURY",
//     "ETHFI",
//     "BOME",
//     "ZEND",
//     "AEVO",
//     "NGL",
//     "STAR",
//     "NIBI",
//     "SCA",
//     "QORPO",
//     "PORTAL",
//     "BBL",
//     "SQT",
//     "CSPR",
//     "CPOOL",
//     "BCUT",
//     "STRK",
//     "HTX",
//     "DYM",
//     "MAVIA",
//     "MXM",
//     "FIRE",
//     "JUP",
//     "DEFI",
//     "DMAIL",
//     "AFG",
//     "GTAI",
//     "FAR",
//     "SAROS",
//     "ONDO",
//     "MANTA",
//     "APP",
//     "DUEL",
//     "SQR",
//     "VIC",
//     "XAI",
//     "AEG",
//     "ZETA",
//     "MYRO",
//     "ALT",
//     "RATS",
//     "SATS",
//     "PORT3",
//     "ZKF",
//     "VPR",
//     "AIOZ",
// ];

// export const listingSPOTTickers3 = [
//     "KCS",
//     "FLIP",
//     "GG",
//     "COQ",
//     "TRC",
//     "AKI",
//     "MBOX",
//     "IRL",
//     "MYRIA",
//     "FMC",
//     "KUB",
//     "CBK",
//     "VANRY",
//     "5IRE",
//     "ROOT",
//     "RPK",
//     "SHRAP",
//     "TOKEN",
//     "MEME",
//     "TIA",
//     "BEAM",
//     "ZTX",
//     "CAT",
//     "LEVER",
//     "KAS",
//     "ORDI",
//     "SEI",
//     "CYBER",
//     "SEILOR",
//     "SPARTA",
//     "NYM",
//     "PENDLE",
//     "VELA",
//     "ZIG",
//     "METH",
//     "JTO",
//     "INSP",
//     "MLK",
//     "VRTX",
//     "PYTH",
//     "POL",
//     "PPT",
//     "JEFF",
//     "FET",
//     "NESS",
//     "NEXT",
//     "CTT",
//     "KAVA",
//     "SAIL",
//     "TAVA",
//     "DSRUN",
//     "PLANET",
//     "WLD",
//     "GSWIFT",
//     "SALD",
//     "ARKM",
//     "ELDA",
//     "TENET",
//     "EGO",
//     "NEON",
//     "MNT",
//     "VELO",
//     "ARTY",
// ];

const tickersJune2020ToNovember2023 = [
    "BTC",
    "BNB",
    "ETH",
    "BCH",
    "XRP",
    "EOS",
    "LTC",
    "TRX",
    "ETC",
    "LINK",
    "XLM",
    "ADA",
    "XMR",
    "DASH",
    "ZEC",
    "XTZ",
    "ATOM",
    "ONT",
    "IOTA",
    "BAT",
    "VET",
    "NEO",
    "QTUM",
    "IOST",
    "THETA",
    // 117минут
];

export const tickersNovember2021ToNovember2023 = [
    "BTC",
    "BNB",
    "ETH",
    "BCH",
    "XRP",
    "EOS",
    "LTC",
    "TRX",
    "ETC",
    "LINK",
    "XLM",
    "ADA",
    "XMR",
    "DASH",
    "ZEC",
    "XTZ",
    "ATOM",
    "ONT",
    "IOTA",
    "BAT",
    "VET",
    "NEO",
    "QTUM",
    "IOST",
    "THETA",
    "ALGO",
    "ZIL",
    "KNC",
    "ZRX",
    "COMP",
    "OMG",
    "DOGE",
    "SXP",
    "KAVA",
    "BAND",
    "RLC",
    "WAVES",
    "MKR",
    "SNX",
    "DOT",
    "YFI",
    "BAL",
    "CRV",
    "TRB",
    "RUNE",
    "SUSHI",
    "EGLD",
    "SOL",
    "ICX",
    "STORJ",
    "BLZ",
    "UNI",
    "AVAX",
    "FTM",
    "ENJ",
    "FLM",
    "REN",
    "KSM",
    "NEAR",
    "AAVE",
    "FIL",
    "RSR",
    "LRC",
    "MATIC",
    "OCEAN",
    "BEL",
    "CTK",
    "AXS",
    "ALPHA",
    "ZEN",
    "SKL",
    "GRT",
    "1INCH",
    "CHZ",
    "LIT",
    "RVN",
    "XEM",
    "SFP",
    "CHR",
    "ONE",
    "HOT",
    "MTL",
    "OGN",
    "NKN",
    "DGB",
    "GTC",
    "C98",
    "ATA",
    "SAND",
    "ANKR",
    "UNFI",
    "REEF",
    "COTI",
    "MANA",
    "HBAR",
    "LINA",
    "STMX",
    "DENT",
    "CELR",
    "ALICE",
    "AR",
    "AUDIO",
    "1000SHIB",
    "BAKE",
    "IOTX",
    "MASK",
    "DYDX",
    "1000XEC",
    "GALA",
    "CELO",
    "KLAY",
    "ARPA",
    "CTSI",
    // 117минут
];

export const tickersNovember2022ToNovember2023 = [
    "BTC",
    "BNB",
    "ETH",
    "BCH",
    "XRP",
    "EOS",
    "LTC",
    "TRX",
    "ETC",
    "LINK",
    "XLM",
    "ADA",
    "XMR",
    "DASH",
    "ZEC",
    "XTZ",
    "ATOM",
    "ONT",
    "IOTA",
    "BAT",
    "VET",
    "NEO",
    "QTUM",
    "IOST",
    "THETA",
    "ALGO",
    "ZIL",
    "KNC",
    "ZRX",
    "COMP",
    "OMG",
    "DOGE",
    "SXP",
    "KAVA",
    "BAND",
    "RLC",
    "WAVES",
    "MKR",
    "SNX",
    "DOT",
    "YFI",
    "BAL",
    "CRV",
    "TRB",
    "RUNE",
    "SUSHI",
    "EGLD",
    "SOL",
    "ICX",
    "STORJ",
    "BLZ",
    "UNI",
    "AVAX",
    "FTM",
    "ENJ",
    "FLM",
    "REN",
    "KSM",
    "NEAR",
    "AAVE",
    "FIL",
    "RSR",
    "LRC",
    "MATIC",
    "OCEAN",
    "BEL",
    "CTK",
    "AXS",
    "ALPHA",
    "ZEN",
    "SKL",
    "GRT",
    "1INCH",
    "CHZ",
    "LIT",
    "RVN",
    "XEM",
    "SFP",
    "CHR",
    "ONE",
    "HOT",
    "MTL",
    "OGN",
    "NKN",
    "DGB",
    "GTC",
    "C98",
    "ATA",
    "LPT",
    "ENS",
    "ANT",
    "IMX",
    "GMT",
    "APE",
    "WOO",
    "DAR",
    "GAL",
    "INJ",
    "STG",
    "LDO",
    "CVX",
    "ICP",
    "APT",
    "QNT",
    "SAND",
    "ANKR",
    "UNFI",
    "REEF",
    "COTI",
    "MANA",
    "HBAR",
    "LINA",
    "STMX",
    "DENT",
    "CELR",
    "ALICE",
    "AR",
    "AUDIO",
    "1000SHIB",
    "BAKE",
    "IOTX",
    "MASK",
    "DYDX",
    "1000XEC",
    "GALA",
    "CELO",
    "KLAY",
    "ARPA",
    "KLAY",
    "ARPA",
    "CTSI",
    "PEOPLE",
    "ROSE",
    "DUSK",
    "FLOW",
    "API3",
    "JASMY",
    "OP",
    "SPELL",
    "1000LUNC",
    "LUNA2",
];

const dateStart4 = new Date(`November 1, 2023 00:00:00`).getTime();
const dateEnd4 = new Date(`November 30, 2023 23:00:00`).getTime();
const url8 = `https://api.bybit.com/derivatives/v3/public/kline?category=linear&symbol=BTCUSDT&interval=60&start=1700863200000&end=1700946000000`;
const url9 = `https://fapi.binance.com/fapi/v1/klines?symbol=BTCUSDT&interval=1h&startTime=1700863200000&endTime=1700946000000`;
